routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\FavouritesController;
use App\Http\Controllers\VotesController;
use App\Models\Question;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('questions', QuestionController::class)->except('show');
Route::get('/questions/{slug}', [QuestionController::class, 'show'])->name('questions.show');
Route::resource('questions.answers', AnswerController::class)->except('show', 'create', 'index');
Route::put('answers/{answer}/best-answer', [AnswerController::class, 'markBestAnswer'])->name('answers.best-answer');
Route::post('questions/{question}/favourite', [FavouritesController::class,  'store'])->name('questions.favourite');
Route::delete('questions/{question}/unfavourite', [FavouritesController::class,  'destroy'])->name('questions.unfavourite');
Route::post('questions/{question}/votes/{vote}', [VotesController::class,'voteQuestion'])->name('questions.vote');
// Route::post('answers/{answer}/votes/{vote}', [VotesController::class,'voteAnswer'])->name('answers.vote');

app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public static function boot() {
        parent::boot();
        static::created(function (Answer $answer) {
            $answer->question->increment('answers_count');
        });
    }

    public function question()
    {
        return $this->belongsTo(Question::class);
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }
    public function getBestAnswerStyleAttribute()
    {
        if($this->id === $this->question->best_answer_id)
        {
            return 'text-success';
        }

        return 'text-dark';
    }
    public function getIsBestAnswerAttribute()
    {
        return ($this->id === $this->question->best_answer_id);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
	use HasFactory, Notifiable;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'name',
		'email',
		'password',
	];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		'password',
		'remember_token',
	];

	/**
	 * The attributes that should be cast to native types.
	 *
	 * @var array
	 */
	protected $casts = [
		'email_verified_at' => 'datetime',
	];
	public function hasQuestionUpVote(Question $question)
	{
		return auth()->user()->votesQuestion()->where(['vote' => 1, 'vote_id' => $question->id, 'vote_type' => Question::class])->exists();
		//ands all condition
	}

	public function hasQuestionDownvote(Question $question)
	{
		return auth()->user()->votesQuestion()
									->where([
										'vote' => -1,
										'vote_id' => $question->id,
										'vote_type' => Question::class,
									])->exists();
	}

    public function hasVoteForQuestion(Question $question)
    {
        return $this->hasQuestionUpVote($question) || $this->hasQuestionDownVote($question);
    }

	public function questions()
	{
		return $this->hasMany(Question::class);
	}

	public function getAvatarAttribute()
	{
		$size = 40;
		$name = $this->name;
		return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}";
	}

	public function favourites(){
		return $this->belongsToMany(Question::class)->withTimestamps();
	}

	public function votesAnswer()
	{
		return $this->morphedByMany(Answer::class, 'vote')->withTimestamps();
	}

	public function votesQuestion()
	{
		return $this->morphedByMany(Question::class, 'vote')->withTimestamps();
	}
}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Answers\CreateAnswerRequest;
use App\Http\Requests\Answers\UpdateAnswerRequest;
use App\Models\Answer;
use App\Models\Question;
use Illuminate\Http\Request;

class AnswerController extends Controller
{
    public function store(CreateAnswerRequest $request, Question $question)
    {
        $question->answers()->create([
            'body' => $request->body,
            'user_id' => auth()->id(),
        ]);
        session()->flash('success', 'Your answer submitted successfully');
        return redirect($question->url);
    }

    public function edit(Question $question, Answer $answer)
    {
        $this->authorize('update', $answer);
        return view('answers.edit', compact(['question', 'answer']));
    }

    public function update(UpdateAnswerRequest $request, Question $question, Answer $answer)
    {
        $this->authorize('update', $answer);
        $answer->update([
            'body' => $request->body
        ]);
        session()->flash('success', 'Your answer has been submitted successfully');
        return redirect($question->url);
    }

    public function destroy(Question $question, Answer $answer)
    {
        $this->authorize('delete', $answer);
        $answer->delete();

        session()->flash('success', 'Your answer has been deleted');
        return redirect()->back();
    }

    public function markBestAnswer(Answer $answer)
    {
        $this->authorize('markAsBest', $answer);
        $answer->question->markAsBest($answer);
        return redirect()->back();
    }
}

resources/views/answers/_create.blade.php
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2>
                        Your Answer
                    </h2>
                </div>
                <div class="card-body">
                    <form action="{{route('questions.answers.store', $question->id)}}" method="POST">
                        @csrf
                        <div class="form-group">
                            <input type="hidden" id="body" name="body" value="{{old('body')}}">
                            <trix-editor input = "body" class="form-control {{$errors->has('body') ? 'is-invalid' : ''}}"
                            ></trix-editor>
                            @error('body')
                                <div class="text-danger">$message</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-success">Submit</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

resources/views/answers/_index.blade.php
<div class="row mt-4">
    <div class="col-md-12 ">
        <div class="card">
            <div class="card-header">
                <h3 class="mt-0">{{Illuminate\Support\Str::plural('Answer', $question->answers_count)}}</h3>
            </div>

            <div class="card-body">
                @foreach ($question->answers as $answer)
                    {!! $answer->body !!}
                    <div class="d-flex justify-content-between mr-3 mt-2">
                        <div class="d-flex">
                            <div class="">
                                <a href="" class="vote-up text-black-50 d-block text-center" title="Up Vote">
                                    <i class="fa fa-caret-up fa-3x"></i>
                                </a>

                                <h4 class="votes-count text-muted text-center m-0">{{$answer->votes_count}}</h4>

                                <a href="" class="vote-down text-black-50 d-block text-center" title="Down Vote">
                                    <i class="fa fa-caret-down fa-3x"></i>
                                </a>
                            </div>

                            <div class="ml-5 mt-3">
                                @can('markAsbest', $answer)
                                    <form action="{{route('answers.best-answer', $answer->id)}}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <button type="submit" class="btn {{$answer->best_answer_style}}" title="Mark as best answer">
                                            <i class="fa fa-check fa-2x"></i>
                                        </button>
                                    </form>

                                @else
                                    @if($answer->is_best_answer)
                                        <i class="fa fa-check fa-2x d-block text-success mb-2"></i>
                                    @endif
                                @endcan

                                {{-- <h4 class="views-count text-muted text-center m-0">{{$answer->views_count}}</h4> --}}
                            </div>
                        </div>

                        <div class="d-flex">
                            @can('update', $answer)
                                <div class="mr-3">
                                    <a href="{{route('questions.answers.edit', [$question->id, $answer->id])}}" class="btn btn-outline-info">Edit</a>
                                </div>
                            @endcan

                            @can('delete', $answer)
                                <form action="{{route('questions.answers.destroy', [$question->id, $answer->id])}}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-outline-danger" onclick="return confirm('Are you sure you want to delete?'">
                                        Delete
                                    </button>
                                </form>
                            @endcan
                        </div>

                        <div class="d-flex flex-column">
                            <div class="text-muted mb-2 text-right">
                                <p>Answered {{$answer->created_date}}</p>
                            </div>
                            <div class="mb-2 d-flex">
                                <div class="">
                                    <img src="{{$answer->author->avatar}}" alt="">
                                </div>
                            </div>
                            <div class="mt-2 ml-1">
                                {{$answer->author->name}}
                            </div>

                        </div>
                    </div>
                    <hr>
                @endforeach
            </div>
        </div>
    </div>
</div>

resources/views/answers/edit.blade.php
@extends('layouts.app')

@section('styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.min.css">
@endsection


@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2>
                        Edit your Answer
                    </h2>
                    <div class="card-body">
                        <form action="{{route('questions.answers.update', [$question->id, $answer->id])}}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <input type="hidden" id="body" name="body" value="{{old('body', $answer->body)}}">
                                <trix-editor input = "body" class="form-control {{$errors->has('body') ? 'is-invalid' : ''}}">

                                </trix-editor>
                                @error('body')
                                    <div class="text-danger">$message</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-success">Edit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
@endsection