routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\FavouritesController;
use App\Http\Controllers\VotesController;
use App\Models\Question;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('questions', QuestionController::class)->except('show');
Route::get('/questions/{slug}', [QuestionController::class, 'show'])->name('questions.show');
Route::resource('questions.answers', AnswerController::class)->except('show', 'create', 'index');
Route::put('answers/{answer}/best-answer', [AnswerController::class, 'markBestAnswer'])->name('answers.best-answer');
Route::post('questions/{question}/favourite', [FavouritesController::class,  'store'])->name('questions.favourite');
Route::delete('questions/{question}/unfavourite', [FavouritesController::class,  'destroy'])->name('questions.unfavourite');
Route::post('questions/{question}/votes/{vote}', [VotesController::class,'voteQuestion'])->name('questions.vote');
// Route::post('answers/{answer}/votes/{vote}', [VotesController::class,'voteAnswer'])->name('answers.vote');

app/Models/Question.php
<?php

namespace App\Models;

use App\Helpers\Votable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Question extends Model
{
    use HasFactory;
    use Votable;
    protected $guarded = ['id'];

    public function getUrlAttribute()
    {
        return "questions/$this->slug";
    }

    public function setTitleAttribute(string $title)
    {
        $this->attributes['title'] = $title;
        $this->attributes['slug'] = Str::slug($title);
    }
    public function getFavouritesCountAttribute()
    {
        return $this->favourites->count();
    }

    public function getIsFavouriteAttribute()
    {
        return $this->favourites()->where('user_id', auth()->id())->count() > 0;
    }

    public function getFavouriteStyleAttribute()
    {
        if($this->getIsFavouriteAttribute())
        {
            return 'text-success';
        }
        return 'text-black-50';
    }

    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }
    public function getAnswerStyleAttribute()
    {
        if($this->answers_count>0)
        {
            if($this->best_answere_id>0)
            {
                return "has-best-answer";
            }
            return "answered";
        }
        return "unanswered";
    }

    public function markAsBest(Answer $answer)
    {
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function favourites()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

    public function vote(int $vote)
    {
        $this->votes()->attach(auth()->id(), ['vote' => $vote]);

        if($vote < 0) {
            $this->decrement('votes_count');
        } else {
            $this->increment('votes_count');
        }
    }

    public function updateVote(int $vote)
    {
        $this->votes()->updateExistingPivot(auth()->id(), ['vote' => $vote]);
        if($vote < 0) {
            $this->decrement('votes_count');
            $this->decrement('votes_count');
        } else {
            $this->increment('votes_count');
            $this->increment('votes_count');
        }
    }

    public function votes()
    {
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
	use HasFactory, Notifiable;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'name',
		'email',
		'password',
	];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		'password',
		'remember_token',
	];

	/**
	 * The attributes that should be cast to native types.
	 *
	 * @var array
	 */
	protected $casts = [
		'email_verified_at' => 'datetime',
	];
	public function hasQuestionUpVote(Question $question)
	{
		return auth()->user()->votesQuestion()->where(['vote' => 1, 'vote_id' => $question->id, 'vote_type' => Question::class])->exists();
		//ands all condition
	}

	public function hasQuestionDownvote(Question $question)
	{
		return auth()->user()->votesQuestion()
									->where([
										'vote' => -1,
										'vote_id' => $question->id,
										'vote_type' => Question::class,
									])->exists();
	}

    public function hasVoteForQuestion(Question $question)
    {
        return $this->hasQuestionUpVote($question) || $this->hasQuestionDownVote($question);
    }

	public function questions()
	{
		return $this->hasMany(Question::class);
	}

	public function getAvatarAttribute()
	{
		$size = 40;
		$name = $this->name;
		return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}";
	}

	public function favourites(){
		return $this->belongsToMany(Question::class)->withTimestamps();
	}

	public function votesAnswer()
	{
		return $this->morphedByMany(Answer::class, 'vote')->withTimestamps();
	}

	public function votesQuestion()
	{
		return $this->morphedByMany(Question::class, 'vote')->withTimestamps();
	}
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Question;
use Illuminate\Http\Request;
use  App\Http\Requests\Question\CreateQuestionRequest;
use App\Http\Requests\Question\UpdateQuestionRequest;
use Illuminate\Support\Facades\Gate;

class QuestionController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth'])->except('index', 'show');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $questions = Question::with('owner')->latest()->paginate(10);
        return view('questions.index',compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('questions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateQuestionRequest $request)
    {
        //
        auth()->user()->questions()->create([
            'title' => $request->title,
            'body' => $request->body
        ]);

        session()->flash('success','Questions has been added successfully');
        return redirect(route('questions.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        $question->increment('views_count');
        return view('questions.show', compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        if($this->authorize('update', $question)) {
            return view('questions.edit', compact('question'));
        }

        abort(403, 'Access Denied');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateQuestionRequest $request, Question $question)
    {
        if($this->authorize('update', $question)) {
            $question->update([
                'title' => $request->title,
                'body'  => $request->body,
            ]);

            session()->flash('success', 'Question has been updated successfully');
            return redirect(route('questions.index'));
        }

        // if(Gate::allows('update-question', $question)) {
        //     $question->update([
        //         'title' => $request->title,
        //         'body'  => $question->body,
        //     ]);

        //     session()->flash('success', 'Question has been updated successfully');
        //     return redirect(route('questions.index'));
        // }

        //abort(403);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        if($this->authorize('delete', $question)) {
            $question->delete();

            session()->flash('success', 'Question has been Deleted');
            return redirect(route('questions.index'));
        }
        // if(auth()->user()->can('delete-question', $question)) {
        //     $question->delete();

        //     session()->flash('success', 'Question has been Deleted');
        //     return redirect(route('questions.index'));
        // }
        abort(403);
    }
}

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2>
                        Ask a Question!
                    </h2>
                    <div class="card-body">
                        <form action="{{route('questions.store')}}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" id="title" name="title" value="{{old('title')}}"
                                class="form-control {{$errors->has('title') ? 'is-invalid' : ''}}">
                                @error('title')
                                    <div class="text-danger">$message</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="">Enter a Question</label>
                                <input type="hidden" id="body" name="body" value="{{old('body')}}">
                                <trix-editor input = "body" class="form-control {{$errors->has('body') ? 'is-invalid' : ''}}"
                                ></trix-editor>
                                @error('body')
                                    <div class="text-danger">$message</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
@endsection

@section('styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.min.css">
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2>
                        Edit a Question!
                    </h2>
                    <div class="card-body">
                        <form action="{{route('questions.update', $question->id)}}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" id="title" name="title" value="{{old('title', $question->title)}}"
                                class="form-control {{$errors->has('title') ? 'is-invalid' : ''}}">
                                @error('title')
                                    <div class="text-danger">$message</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="">Enter a Question</label>
                                <input type="hidden" id="body" name="body" value="{{old('body', $question->body)}}">
                                <trix-editor input = "body" class="form-control {{$errors->has('body') ? 'is-invalid' : ''}}"
                                ></trix-editor>
                                @error('body')
                                    <div class="text-danger">$message</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-success">Edit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
@endsection

@section('styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.min.css">
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="d-flex justify-content-end mb-2">
        <a href="{{ route('questions.create') }}" class="btn btn-outline-primary">Ask a Question!</a>
    </div>
	<div class="row justify-content-center">
		<div class="col-md-12">
			<div class="card card-header">
				<h2>All Questions</h2>
			</div>


			@foreach ($questions as $question )
				<div class="card-body">
					<div class="media">
							<div class="mr-4 statistics">
								<div class="votes text-center mb-3">
									<strong class="d-block">{{$question->votes_count}}</strong> Votes
								</div>
								<div class="answers text-center mb-3 {{$question->answer_style}}">
									<strong class="d-block">{{$question->answers_count}}</strong> Answers
								</div>
								<div class="views text-center mb-3 ">
									<strong class="d-block">{{$question->views_count}}</strong> Views
								</div>

							</div>
							<div class="media-body">
								<div class="d-flex justify-content-between">
									<h4><a href="{{$question->url}}">{{$question->title}}</a></h4>
									<div>
										{{-- Using Gates --}}
										{{-- @if (auth()->check() && auth()->user()->can('update-question',$question))
											<a href="{{route('questions.edit',$question->id)}}" class="btn btn-sm btn-outline-info">Edit</a>
										@endif --}}

										{{-- Using Policies --}}
										@can('update', $question)
											<a href="{{route('questions.edit',$question->id)}}" class="btn btn-sm btn-outline-info">Edit</a>
										@endcan


										{{-- Using Gates --}}
										{{-- @can('delete-question',$question)
											<form action="{{route('questions.destroy', $question->id)}}" method="POST">
												@csrf
												@method('DELETE')
												<button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure you want to delete?')">
													Delete
												</button>
											</form>
										@endcan --}}

										{{-- Using Policies --}}
										@can('delete',$question)
											<form action="{{route('questions.destroy', $question->id)}}" method="POST">
												@csrf
												@method('DELETE')
												<button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure you want to delete?')">
													Delete
												</button>
											</form>
										@endcan

									</div>
                                </div>
									{{-- <div>
										@can('update', $question)
											<a href="{{route('questions.edit', $question->id)}}" class="btn btn-sm btn-outline-info">Edit</a>
										@endcan

										@can ('delete-question', $question)
											<form action="{{route('questions.destroy', $question->id)}}" method="POST">
												@csrf
												@method('DELETE')
												<button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure you want to delete?')">Delete</button>
											</form>
										@endcan
									</div> --}}
                                    <p>
                                        Asked By: <a href="#">{{$question->owner->name}}</a>
                                        <span class="text-muted">{{$question->created_date}}</span>
                                    </p>
                                    <p>{!! \Illuminate\Support\Str::limit($question->body, 255) !!}</p>
						   </div>
					</div>
				</div>
				<hr>
			@endforeach
			<div class="class-footer">
				{{$questions->links()}}
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('styles')
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.min.css">
@endsection


@section('content')
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-12 ">
				<div class="card">
					<div class="card-header">
						<h1>{{$question->title}}</h1>
					</div>

					<div class="card-body">
						{!! $question->body !!}
					</div>

					<div class="card-footer">
						<div class="d-flex justify-content-between mr-3 mt-2">
							<div class="d-flex">
								<div class="">
									@auth
										<form action="{{route('questions.vote', [$question->id, 1])}}" method="POST">
											@csrf
											<button type="submit" title="Up Vote"
                                                class="btn {{auth()->user()->hasQuestionUpvote($question) ? 'text-dark' : 'text-black-50'}}">
												<i class="fa fa-caret-up fa-3x"></i>
											</button>
										</form>
									@else
                                        <a href="{{route('login')}}" class="vote-up text-black-50 d-block text-center" title="Up Vote">
                                            <i class="fa fa-caret-up fa-3x"></i>
                                        </a>
									@endauth

									<h4 class="votes-count text-muted text-center m-0">{{$question->votes_count}}</h4>

                                    @auth
                                    <form action="{{route('questions.vote', [$question->id, -1])}}" method="POST">
                                        @csrf
                                        <button type="submit" title="Down Vote" class="btn {{auth()->user()->hasQuestionDownvote($question) ? 'text-dark' : 'text-black-50'}}">
                                            <i class="fa fa-caret-down fa-3x"></i>
                                        </button>
                                    </form>
                                    @else
                                        <a href="{{route('login')}}" class="vote-down text-black-50 d-block text-center">
                                            <i class="fa fa-caret-down fa-3x"></i>
                                        </a>
                                    @endauth
								</div>

								<div class="ml-5 mt-3">
									{{-- <a href="" title="Mark as favourite" class="favourite text-dark text-center text-block">
										<i class="fa fa-star fa-2x"></i>
									</a> --}}

									@can('markAsFavourite', $question)
									<form action="{{route($question->is_favourite ? 'questions.unfavourite' : 'questions.favourite', $question->id)}}" method="POST">
										@csrf
										@if($question->is_favourite)
											@method('DELETE')
										@endif

										<button type="submit" class="btn {{$question->favourite_style}}">
											<i class="fa fa-star fa-2x"></i>
										</button>
									</form>
									@else
										<i class="fa fa-star-o text-success d-block fa-2x"></i>
									@endcan

									<h4 class="views-count text-muted text-center m-0 {{ $question->favourite_style}} text-center m-0">{{$question->favourites_count}}</h4>
								</div>
							</div>

							<div class="d-flex flex-column">
								<div class="text-muted mb-2 text-right">
									<p>Asked {{$question->created_date}}</p>
								</div>
								<div class="mb-2 d-flex">
									<div class="">
										<img src="{{$question->owner->avatar}}" alt="">
									</div>
								</div>
								<div class="mt- ml-2">
									{{$question->owner->name}}
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		@include('answers._index')
		@include('answers._create')
	</div>
@endsection

@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
@endsection